pricesmap/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from django.conf import settings

from pricesmap.webapp.views import home


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    # for everything else, load url from webapp.urls
    url(r'^pm/', include('pricesmap.webapp.urls')),
    url(r'^/?$', home , name='home'),
)

pricesmap/webapp/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

class AboutView(TemplateView):

    template_name = "about.html"
urlpatterns = patterns('pricesmap.webapp.views',
    url(r'^p/(?P<type>\w+)/?$', 'detail', name='detail'),
    url(r'^p/(?P<type>\w+)/add/?$', 'add', name='add'),
    url(r'^p/report/(?P<id>\w+)/?$', 'report', name='report'),

)

urlpatterns += patterns('',
    url(r'^about/?$', AboutView.as_view(), name="about")
)

pricesmap/webapp/models.py
# -*- coding: utf8 -*-
from django.db import models
from django.contrib import admin

import pricesmap.settings_test as settings

class Produit(models.Model):
    """
    Représente un type de produit
    """

    name = models.CharField(max_length=200)
    url_name = models.SlugField(max_length=20)
    description = models.TextField(
        help_text="Peut contenir du HTML pour la mise en forme. Ne sera pas vérifié lors de l'affichage (mark_safe)"
    )

    def __unicode__(self):
        return self.name


class Item(models.Model):
    """
    Représente une entrée pour un produit donné
    """

    prix = models.DecimalField(max_digits=4, decimal_places=2)
    submitter_email = models.EmailField()
    date = models.DateField(auto_now_add=True)
    comment = models.CharField(max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    reported = models.BooleanField(default=False, blank=True)

    # foreign key
    produit = models.ForeignKey('Produit')

    def __unicode__(self):
        return self.produit.name+'@'+str(self.id)

# ADMIN
admin.site.register(Produit)
admin.site.register(Item)

pricesmap/webapp/forms.py
from django.forms import ModelForm

from pricesmap.webapp.models import Item

class ItemForm(ModelForm):

    class Meta:
        model = Item

        exclude = ('date', 'produit')

pricesmap/webapp/views.py
# -*- coding:utf8 -*-

from django.shortcuts import\
        get_object_or_404,\
        render_to_response,\
        redirect,\
        RequestContext
from django.core.urlresolvers import reverse
from django.http import Http404
from django.contrib import messages

from pricesmap.webapp.models import *
from pricesmap.webapp.forms import ItemForm

def home(request):
    types = Produit.objects.all()

    return render_to_response(
        'home.html',
        {
            'types': types
        },
        context_instance=RequestContext(request)
    )

def detail(request, type):

    produit = get_object_or_404(Produit, url_name=type)
    items = produit.item_set.all().filter(reported=False)
    form = ItemForm()

    return render_to_response(
        'detail.html',
        {
            'produit': produit,
            'items': items,
            'form': form
        },
        context_instance=RequestContext(request)
    )


def add(request, type):

    if request.method == 'POST':

        produit = get_object_or_404(Produit, url_name=type)

        form = ItemForm(request.POST)
        if form.is_valid():

            item = Item()
            item.prix = form.cleaned_data['prix']
            item.latitude = form.cleaned_data['latitude']
            item.longitude = form.cleaned_data['longitude']
            item.submitter_email = form.cleaned_data['submitter_email']
            item.comment = form.cleaned_data['comment']

            item.produit = produit

            item.save()

        else:
            messages.error(request, "Le formulaire rempli n'était pas valide....")


    return redirect(reverse('detail', args=(str(type),)))

def report(request, id):
    """If a item gets reported, it disapear from the list, waiting for an admin to verify it"""

    item = get_object_or_404(Item, pk=id)
    item.reported = True
    item.save()

    messages.success(request, "L'information a bien été marquée comme 'A vérifier'. Merci !")
    return redirect(reverse('detail', args=(str(item.produit.url_name),)))

pricesmap/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>PricesMap{% block title %}{%endblock %}</title>

		<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}"/>
		<script type="text/javascript" src="{% static "js/jquery202.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
		<style>
			/* ensure the content is not under the top bar */
			body { padding-top: 60px; }
		</style>

		{% block extraHead %}{% endblock %}
	</head>
	<body>
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a href="/" class="brand">PricesMap</a>
					<ul class="nav">
						{% block menu %}
						{% endblock %}
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

pricesmap/webapp/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-right">A propos de PricesMap</h1>
	<h3>Pourquoi PricesMap ?</h3>
	<p>L'idée m'est venue après divers appels sur Twitter : un particulier dans le sud de la France, puis la mairie de Paris à
	propos du prix du café.</p>
	<p>Aujourd'hui, certains produits largement distribués voient leur prix fluctuer énormément et il est souvent dur de savoir
	où aller pour ne pas se faire avoir.</p>

	<h3>Comment ça marche ?</h3>
	<p>Vous choisissez le produit qui vous intéresse <a class="reference external" href="/">ici</a> et vous avez alors accès à la carte des prix de ce produit.</p>
	<p>Pour ajouter un emplacement à la carte , cliquez simplement là où vous voulez placer le marqueur et renseignez le
	formulaire.</p>
{% endblock %}

pricesmap/webapp/templates/detail.html
{% extends "base.html" %}

{% load geo %}

{% block extraHead %}
	<!-- Leaflet CDN -->
	<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.css" />
	<!--[if lte IE 8]>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.ie.css" />
	<![endif]-->

	<script src="http://cdn.leafletjs.com/leaflet-0.5/leaflet.js"></script>


	<style>
		/* Define height for map section */
		#map {
			margin-top: 40px;
			height: 600px;
		}
	</style>

{% endblock %}

{% block content %}

{% if messages %}
{% for m in messages %}
<div class="alert alert-{{m.tags}}">
	{{m}}
	<button class="close" data-dismiss="alert" type="button">×</button>
</div>
{% endfor %}
{% endif %}

<h1 id="topline">{{produit}}</h1>

<div class="row-fluid">
	<div class="span7">
		{{produit.description|safe}}
	</div>

	<div class="span5">
		<h2>Participer</h2>
		<form action="{% url 'add' produit.url_name %}" method="post">
			{% csrf_token %}

			{{form.as_p}}
			<input type="submit" class="btn btn-primary" value="Ajouter"/>
		</form>
	</div>
</div>

<div id="map"></div>

<script type="text/javascript">
	// initialize the map...
	var map = L.map('map').setView([46.7, 4.19], 5);

	// ... load tile layer ...
	L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
	}).addTo(map);

	// ... add markers and popups
	{% for i in items %}
	L.marker([{{i.latitude|sep}}, {{i.longitude|sep}}]).addTo(map)
		.bindPopup('<h4>{{i.prix}}€</h4><br><p>{{i.comment}}</p><p class="text-right text-error"><a href="{% url 'report' i.id %}">Signaler</a></p>')
	{% endfor %}

	var clicked_marker;
	map.on('click', function onMapClick(e) {
		if (clicked_marker) {
			map.removeLayer(clicked_marker);
		}
		$('#id_latitude').attr('value', e.latlng.lat);
		$('#id_longitude').attr('value', e.latlng.lng);

		clicked_marker = new L.marker(e.latlng).addTo(map)
			.bindPopup('Ajoutez un prix à cette carte en remplissant <a href="#topline">le formulaire</a>.<br>Les coordonnées sont celles du point que vous venez de cliquer')
			.openPopup();
	});
</script>
{% endblock %}

pricesmap/webapp/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="hero-unit">

	<h1>PricesMap</h1>
	<p>On cherche souvent à connaitre les prix de certaines choses autour de nous... PricesMap est là pour ça !</p>
	<p>Selectionnez un produit pour en savoir plus !</p>
	<div class="pagination pagination-centered">
		<ul>
		{% for t in types %}
			<li><a href="{% url 'detail' t.url_name %}">{{t}}</a></li>
		{% endfor %}
		</ul>
	</div>

</div>
{% endblock %}